filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /zex/logs/debug.log
      - /zex/logs/error.log
    json.keys_under_root: true
    json.add_error_key: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

logging.json: true
