USDT_MAINNET = "POL:1"

TAGS = {
    "BTC:1": "btc",
    "XMR:1": "xmr",
    "POL:1": "usdt",
    "POL:2": "usdc",
    "POL:3": "wbtc",
    "POL:4": "link",
    "BSC:1": "usdt",
    "BSC:2": "usdc",
    "BSC:3": "wbtc",
    "BSC:4": "link",
    "ARB:1": "usdt",
    "ARB:2": "usdc",
    "ARB:3": "wbtc",
    "ARB:4": "link",
    "OPT:1": "usdt",
    "OPT:2": "usdc",
    "OPT:3": "wbtc",
    "OPT:4": "link",
}

CHAIN_TYPES = {
    "BTC": "native_only",
    "XMR": "native_only",
    "POL": "evm",
    "BSC": "evm",
    "ARB": "evm",
    "OPT": "evm",
}

NAMES = {
    "BTC:1": "Bitcoin",
    "XMR:1": "Monero",
    "POL:1": "USD Tether",
    "POL:2": "USD coin",
    "POL:3": "Wrapped Bitcoin",
    "POL:4": "ChainLink",
    "BSC:1": "USD Tether",
    "BSC:2": "USD coin",
    "BSC:3": "Wrapped Bitcoin",
    "BSC:4": "ChainLink",
    "ARB:1": "USD Tether",
    "ARB:2": "USD coin",
    "ARB:3": "Wrapped Bitcoin",
    "ARB:4": "ChainLink",
    "OPT:1": "USD Tether",
    "OPT:2": "USD coin",
    "OPT:3": "Wrapped Bitcoin",
    "OPT:4": "ChainLink",
}

SYMBOLS = {
    "BTC:1": "BTC",
    "XMR:1": "XMR",
    "POL:1": "USDT",
    "POL:2": "USDC",
    "POL:3": "WBTC",
    "POL:4": "LINK",
    "BSC:1": "USDT",
    "BSC:2": "USDC",
    "BSC:3": "WBTC",
    "BSC:4": "LINK",
    "ARB:1": "USDT",
    "ARB:2": "USDC",
    "ARB:3": "WBTC",
    "ARB:4": "LINK",
    "OPT:1": "USDT",
    "OPT:2": "USDC",
    "OPT:3": "WBTC",
    "OPT:4": "LINK",
}
