state_manager:
  host: "0.0.0.0" # optional
  port: 15783 # optional
  api_prefix: "/v1"
  state_dest: state/zex_state.pb
  verbose: true

  redis:
    url: 127.0.0.1:6379
    password: zex_super_secure_password
